/**
 * Pure builder: tokens.json → Tailwind v4 CSS (docs/13-design-system.md).
 * Kept free of Node APIs so it can be unit-tested and reused by the generator script.
 *
 * Output structure:
 *  - :root / .dark  → semantic colour custom properties (runtime theme switching)
 *  - @theme inline  → maps Tailwind colour utilities (bg-background, text-link, …) to those properties
 *  - @theme         → fonts, type scale, radius, shadows, containers, easing
 * Raw palette values are never exposed as utilities, so components can only use semantic colours.
 */

export type Tokens = {
  color: { light: Record<string, string>; dark: Record<string, string> };
  font: Record<string, string>;
  text: Record<string, { size: string; lineHeight: string; letterSpacing: string }>;
  radius: Record<string, string>;
  shadow: Record<string, string>;
  container: Record<string, string>;
  motion: {
    duration: Record<string, number>;
    ease: Record<string, [number, number, number, number]>;
  };
};

const HEADER = `/* AUTO-GENERATED by scripts/generate-tokens.ts from src/styles/tokens.json. Do not edit. */`;

function block(selector: string, lines: string[]): string {
  return `${selector} {\n${lines.map((l) => `  ${l}`).join("\n")}\n}`;
}

export function buildTokensCss(tokens: Tokens): string {
  const { light, dark } = tokens.color;

  const lightKeys = Object.keys(light).sort();
  const darkKeys = Object.keys(dark).sort();
  const missing = lightKeys.filter((k) => !(k in dark));
  const extra = darkKeys.filter((k) => !(k in light));
  if (missing.length || extra.length) {
    throw new Error(
      `Theme token mismatch. Missing in dark: [${missing.join(", ")}]; only in dark: [${extra.join(", ")}]`,
    );
  }

  const root = block(":root", [
    "color-scheme: light;",
    ...lightKeys.map((k) => `--${k}: ${light[k]};`),
  ]);
  const darkBlock = block(".dark", [
    "color-scheme: dark;",
    ...lightKeys.map((k) => `--${k}: ${dark[k]};`),
  ]);

  const themeInline = block(
    "@theme inline",
    lightKeys.map((k) => `--color-${k}: var(--${k});`),
  );

  const theme = block("@theme", [
    ...Object.entries(tokens.font).map(([k, v]) => `--font-${k}: ${v};`),
    `--font-display--font-variation-settings: "SOFT" 50, "WONK" 0;`,
    ...Object.entries(tokens.text).flatMap(([k, v]) => [
      `--text-${k}: ${v.size};`,
      `--text-${k}--line-height: ${v.lineHeight};`,
      `--text-${k}--letter-spacing: ${v.letterSpacing};`,
    ]),
    ...Object.entries(tokens.radius).map(([k, v]) => `--radius-${k}: ${v};`),
    ...Object.entries(tokens.shadow).map(([k, v]) => `--shadow-${k}: ${v};`),
    ...Object.entries(tokens.container).map(([k, v]) => `--container-${k}: ${v};`),
    ...Object.entries(tokens.motion.ease).map(
      ([k, v]) => `--ease-${k}: cubic-bezier(${v.join(", ")});`,
    ),
  ]);

  return [HEADER, root, darkBlock, themeInline, theme].join("\n\n") + "\n";
}
